### ISSUE TITLE
Success with kernel 4.15 / Ubuntu 18.04 (b2)

### ISSUE THREAD

**Issue by dannynicolas** [jurobystricky/Netgear-A6210#108]
I was able to get this working via the 4.15 branch (https://github.com/kaduke/Netgear-A6210/tree/port-to-4.15). I'm on the latest beta release of 18.04 Ubuntu (64 bit / 4.15.0-19-generic kernel), with a fresh install.

**Comment by ajsingh007** [comment]
I just got ubuntu 18.04 LTS and was able to successfully make and make install using the above link. However, I still get the **No Wi-Fi Adapter Found** message in Settings after restarting and running `sudo service network-manager restart`

Any insight or advice? Thanks!

**Comment by dannynicolas** [comment]
I would unplug the USB device, then plug it in and see if it recognizes it. if it doesn't see the device still, try restarting again.

**Comment by ajsingh007** [comment]
Appreciate the rapid response! That literally worked right now, perhaps because I also disabled secure boot? Anyway, thank you for posting the 4.15 -- it is what I needed!

**Comment by lahans** [comment]
nice work. For 17.x I had to tweak the code myself to get it working:)

Has anyone experienced after the computer is idling, that network stops working? I don't get much in the log files other than wlan0: link not ready. Then I restart my machine in order to get network again:(

I have tried take out the adapter and put it back in without luck

**Comment by MiscellaneousMemphian** [comment]
Yes I can not get any wireless network to appear I am using Ubuntu 18.04 LTS.

**Comment by krdeepak** [comment]
Did someone get it working for latest ubuntu 18.04.2 which has kernel 4.18.0-15-generic ?
